[build]
  command   = "npm run build"
  publish   = "build"
  functions = "functions"

# Point root redirects to index.html
[[redirects]]
  from = "/*"
  :contentReference[oaicite:1]{index=1}
  status = 200
